// AUTO-GENERATED by Supabase MCP - do not edit manually.
// Regenerate with: supabase gen types typescript --project-id hvlwkmyftnrasebecaet
// Generated: 2026-05-22

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      activity_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          diff_json: Json | null
          entity_id: string
          entity_type: string
          id: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          diff_json?: Json | null
          entity_id: string
          entity_type: string
          id?: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          diff_json?: Json | null
          entity_id?: string
          entity_type?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "activity_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
        ]
      }
      app_users: {
        Row: {
          avatar_url: string | null
          created_at: string
          created_by: string | null
          deleted_at: string | null
          email: string | null
          full_name: string | null
          id: string
          is_active: boolean
          organization_id: string | null
          phone: string | null
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          email?: string | null
          full_name?: string | null
          id: string
          is_active?: boolean
          organization_id?: string | null
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          email?: string | null
          full_name?: string | null
          id?: string
          is_active?: boolean
          organization_id?: string | null
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "app_users_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      attachments: {
        Row: {
          created_at: string
          created_by: string | null
          deleted_at: string | null
          entity_id: string
          entity_type: string
          filename: string
          id: string
          mime_type: string | null
          path: string
          size_bytes: number | null
          updated_at: string
          updated_by: string | null
          uploaded_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          entity_id: string
          entity_type: string
          filename: string
          id?: string
          mime_type?: string | null
          path: string
          size_bytes?: number | null
          updated_at?: string
          updated_by?: string | null
          uploaded_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          entity_id?: string
          entity_type?: string
          filename?: string
          id?: string
          mime_type?: string | null
          path?: string
          size_bytes?: number | null
          updated_at?: string
          updated_by?: string | null
          uploaded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "attachments_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
        ]
      }
      client_addresses: {
        Row: {
          client_id: string
          country_id: string | null
          created_at: string
          created_by: string | null
          deleted_at: string | null
          id: string
          line1: string | null
          line2: string | null
          postal_code: string | null
          region: string | null
          type: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          client_id: string
          country_id?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          line1?: string | null
          line2?: string | null
          postal_code?: string | null
          region?: string | null
          type?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          client_id?: string
          country_id?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          line1?: string | null
          line2?: string | null
          postal_code?: string | null
          region?: string | null
          type?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "client_addresses_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "client_addresses_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
        ]
      }
      client_contacts: {
        Row: {
          client_id: string
          created_at: string
          created_by: string | null
          deleted_at: string | null
          email: string | null
          id: string
          is_primary: boolean
          name: string
          notes: string | null
          phone: string | null
          role: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          client_id: string
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          email?: string | null
          id?: string
          is_primary?: boolean
          name: string
          notes?: string | null
          phone?: string | null
          role?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          client_id?: string
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          email?: string | null
          id?: string
          is_primary?: boolean
          name?: string
          notes?: string | null
          phone?: string | null
          role?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "client_contacts_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
        ]
      }
      clients: {
        Row: {
          account_owner_id: string | null
          country_id: string | null
          created_at: string
          created_by: string | null
          deleted_at: string | null
          giro: string | null
          id: string
          is_active: boolean
          legal_name: string | null
          name: string
          notes: string | null
          region: string | null
          source: string | null
          tax_id: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          account_owner_id?: string | null
          country_id?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          giro?: string | null
          id?: string
          is_active?: boolean
          legal_name?: string | null
          name: string
          notes?: string | null
          region?: string | null
          source?: string | null
          tax_id?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          account_owner_id?: string | null
          country_id?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          giro?: string | null
          id?: string
          is_active?: boolean
          legal_name?: string | null
          name?: string
          notes?: string | null
          region?: string | null
          source?: string | null
          tax_id?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "clients_account_owner_id_fkey"
            columns: ["account_owner_id"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "clients_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
        ]
      }
      comments: {
        Row: {
          body: string
          created_at: string
          created_by: string | null
          deleted_at: string | null
          entity_id: string
          entity_type: string
          id: string
          mentions: string[]
          parent_id: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          body: string
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          entity_id: string
          entity_type: string
          id?: string
          mentions?: string[]
          parent_id?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          body?: string
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          entity_id?: string
          entity_type?: string
          id?: string
          mentions?: string[]
          parent_id?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "comments_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "comments"
            referencedColumns: ["id"]
          },
        ]
      }
      contract_amendments: {
        Row: {
          applied_at: string
          contract_id: string
          created_at: string
          created_by: string | null
          deleted_at: string | null
          diff_json: Json
          id: string
          reason: string | null
          type: Database["public"]["Enums"]["amendment_type"]
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          applied_at?: string
          contract_id: string
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          diff_json: Json
          id?: string
          reason?: string | null
          type: Database["public"]["Enums"]["amendment_type"]
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          applied_at?: string
          contract_id?: string
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          diff_json?: Json
          id?: string
          reason?: string | null
          type?: Database["public"]["Enums"]["amendment_type"]
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contract_amendments_contract_id_fkey"
            columns: ["contract_id"]
            isOneToOne: false
            referencedRelation: "contracts"
            referencedColumns: ["id"]
          },
        ]
      }
      contract_items: {
        Row: {
          contract_id: string
          created_at: string
          created_by: string | null
          currency: Database["public"]["Enums"]["currency_code"]
          deleted_at: string | null
          delivery_month: number | null
          delivery_week: number
          delivery_year: number
          format: string | null
          genetic_program_id: string | null
          id: string
          legacy_excel_row: number | null
          material_type: Database["public"]["Enums"]["material_type"] | null
          notes: string | null
          qty_delivered: number
          qty_plants: number
          status: Database["public"]["Enums"]["delivery_status"]
          unit_price: number
          updated_at: string
          updated_by: string | null
          variety_id: string
        }
        Insert: {
          contract_id: string
          created_at?: string
          created_by?: string | null
          currency: Database["public"]["Enums"]["currency_code"]
          deleted_at?: string | null
          delivery_month?: number | null
          delivery_week: number
          delivery_year: number
          format?: string | null
          genetic_program_id?: string | null
          id?: string
          legacy_excel_row?: number | null
          material_type?: Database["public"]["Enums"]["material_type"] | null
          notes?: string | null
          qty_delivered?: number
          qty_plants: number
          status?: Database["public"]["Enums"]["delivery_status"]
          unit_price: number
          updated_at?: string
          updated_by?: string | null
          variety_id: string
        }
        Update: {
          contract_id?: string
          created_at?: string
          created_by?: string | null
          currency?: Database["public"]["Enums"]["currency_code"]
          deleted_at?: string | null
          delivery_month?: number | null
          delivery_week?: number
          delivery_year?: number
          format?: string | null
          genetic_program_id?: string | null
          id?: string
          legacy_excel_row?: number | null
          material_type?: Database["public"]["Enums"]["material_type"] | null
          notes?: string | null
          qty_delivered?: number
          qty_plants?: number
          status?: Database["public"]["Enums"]["delivery_status"]
          unit_price?: number
          updated_at?: string
          updated_by?: string | null
          variety_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "contract_items_contract_id_fkey"
            columns: ["contract_id"]
            isOneToOne: false
            referencedRelation: "contracts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contract_items_genetic_program_id_fkey"
            columns: ["genetic_program_id"]
            isOneToOne: false
            referencedRelation: "genetic_programs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contract_items_variety_id_fkey"
            columns: ["variety_id"]
            isOneToOne: false
            referencedRelation: "varieties"
            referencedColumns: ["id"]
          },
        ]
      }
      contract_versions: {
        Row: {
          contract_id: string
          created_at: string
          created_by: string | null
          deleted_at: string | null
          frozen_at: string
          id: string
          pdf_url: string | null
          snapshot_json: Json
          updated_at: string
          updated_by: string | null
          version_n: number
        }
        Insert: {
          contract_id: string
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          frozen_at?: string
          id?: string
          pdf_url?: string | null
          snapshot_json: Json
          updated_at?: string
          updated_by?: string | null
          version_n: number
        }
        Update: {
          contract_id?: string
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          frozen_at?: string
          id?: string
          pdf_url?: string | null
          snapshot_json?: Json
          updated_at?: string
          updated_by?: string | null
          version_n?: number
        }
        Relationships: [
          {
            foreignKeyName: "contract_versions_contract_id_fkey"
            columns: ["contract_id"]
            isOneToOne: false
            referencedRelation: "contracts"
            referencedColumns: ["id"]
          },
        ]
      }
      contracts: {
        Row: {
          client_id: string
          condition: Database["public"]["Enums"]["condition_type"]
          created_at: string
          created_by: string | null
          currency: Database["public"]["Enums"]["currency_code"]
          deleted_at: string | null
          fx_rate_to_usd: number | null
          id: string
          incoterm: string | null
          notes: string | null
          number: string
          organization_id: string
          sale_type: Database["public"]["Enums"]["sale_type"] | null
          signed_at: string | null
          source_opportunity_id: string | null
          status: Database["public"]["Enums"]["contract_status"]
          total_iva: number
          total_neto: number
          total_neto_usd: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          client_id: string
          condition?: Database["public"]["Enums"]["condition_type"]
          created_at?: string
          created_by?: string | null
          currency: Database["public"]["Enums"]["currency_code"]
          deleted_at?: string | null
          fx_rate_to_usd?: number | null
          id?: string
          incoterm?: string | null
          notes?: string | null
          number: string
          organization_id: string
          sale_type?: Database["public"]["Enums"]["sale_type"] | null
          signed_at?: string | null
          source_opportunity_id?: string | null
          status?: Database["public"]["Enums"]["contract_status"]
          total_iva?: number
          total_neto?: number
          total_neto_usd?: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          client_id?: string
          condition?: Database["public"]["Enums"]["condition_type"]
          created_at?: string
          created_by?: string | null
          currency?: Database["public"]["Enums"]["currency_code"]
          deleted_at?: string | null
          fx_rate_to_usd?: number | null
          id?: string
          incoterm?: string | null
          notes?: string | null
          number?: string
          organization_id?: string
          sale_type?: Database["public"]["Enums"]["sale_type"] | null
          signed_at?: string | null
          source_opportunity_id?: string | null
          status?: Database["public"]["Enums"]["contract_status"]
          total_iva?: number
          total_neto?: number
          total_neto_usd?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contracts_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contracts_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contracts_source_opportunity_id_fkey"
            columns: ["source_opportunity_id"]
            isOneToOne: false
            referencedRelation: "opportunities"
            referencedColumns: ["id"]
          },
        ]
      }
      countries: {
        Row: {
          created_at: string
          created_by: string | null
          deleted_at: string | null
          id: string
          iso2: string
          iso3: string
          lat: number | null
          lon: number | null
          name_en: string
          name_es: string
          region: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          iso2: string
          iso3: string
          lat?: number | null
          lon?: number | null
          name_en: string
          name_es: string
          region?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          iso2?: string
          iso3?: string
          lat?: number | null
          lon?: number | null
          name_en?: string
          name_es?: string
          region?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      deliveries: {
        Row: {
          contract_item_id: string
          created_at: string
          created_by: string | null
          deleted_at: string | null
          delivered_at: string
          id: string
          notes: string | null
          qty_delivered: number
          remito_number: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          contract_item_id: string
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          delivered_at: string
          id?: string
          notes?: string | null
          qty_delivered: number
          remito_number?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          contract_item_id?: string
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          delivered_at?: string
          id?: string
          notes?: string | null
          qty_delivered?: number
          remito_number?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "deliveries_contract_item_id_fkey"
            columns: ["contract_item_id"]
            isOneToOne: false
            referencedRelation: "contract_items"
            referencedColumns: ["id"]
          },
        ]
      }
      genetic_programs: {
        Row: {
          created_at: string
          created_by: string | null
          default_royalty_pct: number
          default_royalty_per_plant: number
          deleted_at: string | null
          id: string
          name: string
          notes: string | null
          owner: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          default_royalty_pct?: number
          default_royalty_per_plant?: number
          deleted_at?: string | null
          id?: string
          name: string
          notes?: string | null
          owner?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          default_royalty_pct?: number
          default_royalty_per_plant?: number
          deleted_at?: string | null
          id?: string
          name?: string
          notes?: string | null
          owner?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string
          created_by: string | null
          deleted_at: string | null
          id: string
          link: string | null
          payload: Json | null
          read_at: string | null
          title: string
          type: string
          updated_at: string
          updated_by: string | null
          user_id: string
        }
        Insert: {
          body?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          link?: string | null
          payload?: Json | null
          read_at?: string | null
          title: string
          type: string
          updated_at?: string
          updated_by?: string | null
          user_id: string
        }
        Update: {
          body?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          link?: string | null
          payload?: Json | null
          read_at?: string | null
          title?: string
          type?: string
          updated_at?: string
          updated_by?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
        ]
      }
      opportunities: {
        Row: {
          client_id: string | null
          client_name_raw: string | null
          created_at: string
          created_by: string | null
          currency: Database["public"]["Enums"]["currency_code"]
          deleted_at: string | null
          estimated_value: number | null
          estimated_value_usd: number | null
          expected_close_date: string | null
          id: string
          lost_reason: string | null
          name: string
          notes: string | null
          organization_id: string
          owner_id: string | null
          probability_pct: number
          source: string | null
          stage_id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          client_id?: string | null
          client_name_raw?: string | null
          created_at?: string
          created_by?: string | null
          currency?: Database["public"]["Enums"]["currency_code"]
          deleted_at?: string | null
          estimated_value?: number | null
          estimated_value_usd?: number | null
          expected_close_date?: string | null
          id?: string
          lost_reason?: string | null
          name: string
          notes?: string | null
          organization_id: string
          owner_id?: string | null
          probability_pct: number
          source?: string | null
          stage_id: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          client_id?: string | null
          client_name_raw?: string | null
          created_at?: string
          created_by?: string | null
          currency?: Database["public"]["Enums"]["currency_code"]
          deleted_at?: string | null
          estimated_value?: number | null
          estimated_value_usd?: number | null
          expected_close_date?: string | null
          id?: string
          lost_reason?: string | null
          name?: string
          notes?: string | null
          organization_id?: string
          owner_id?: string | null
          probability_pct?: number
          source?: string | null
          stage_id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "opportunities_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "opportunities_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "opportunities_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "opportunities_stage_id_fkey"
            columns: ["stage_id"]
            isOneToOne: false
            referencedRelation: "opportunity_stages"
            referencedColumns: ["id"]
          },
        ]
      }
      opportunity_activities: {
        Row: {
          body: string | null
          created_at: string
          created_by: string | null
          deleted_at: string | null
          done_at: string | null
          due_at: string | null
          id: string
          opportunity_id: string
          owner_id: string | null
          subject: string
          type: Database["public"]["Enums"]["activity_type"]
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          body?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          done_at?: string | null
          due_at?: string | null
          id?: string
          opportunity_id: string
          owner_id?: string | null
          subject: string
          type: Database["public"]["Enums"]["activity_type"]
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          body?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          done_at?: string | null
          due_at?: string | null
          id?: string
          opportunity_id?: string
          owner_id?: string | null
          subject?: string
          type?: Database["public"]["Enums"]["activity_type"]
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "opportunity_activities_opportunity_id_fkey"
            columns: ["opportunity_id"]
            isOneToOne: false
            referencedRelation: "opportunities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "opportunity_activities_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
        ]
      }
      opportunity_items: {
        Row: {
          created_at: string
          created_by: string | null
          currency: Database["public"]["Enums"]["currency_code"] | null
          deleted_at: string | null
          expected_delivery_week: number | null
          expected_delivery_year: number | null
          format: string | null
          id: string
          notes: string | null
          opportunity_id: string
          qty_plants_est: number
          unit_price_est: number | null
          updated_at: string
          updated_by: string | null
          variety_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          currency?: Database["public"]["Enums"]["currency_code"] | null
          deleted_at?: string | null
          expected_delivery_week?: number | null
          expected_delivery_year?: number | null
          format?: string | null
          id?: string
          notes?: string | null
          opportunity_id: string
          qty_plants_est: number
          unit_price_est?: number | null
          updated_at?: string
          updated_by?: string | null
          variety_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          currency?: Database["public"]["Enums"]["currency_code"] | null
          deleted_at?: string | null
          expected_delivery_week?: number | null
          expected_delivery_year?: number | null
          format?: string | null
          id?: string
          notes?: string | null
          opportunity_id?: string
          qty_plants_est?: number
          unit_price_est?: number | null
          updated_at?: string
          updated_by?: string | null
          variety_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "opportunity_items_opportunity_id_fkey"
            columns: ["opportunity_id"]
            isOneToOne: false
            referencedRelation: "opportunities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "opportunity_items_variety_id_fkey"
            columns: ["variety_id"]
            isOneToOne: false
            referencedRelation: "varieties"
            referencedColumns: ["id"]
          },
        ]
      }
      opportunity_stages: {
        Row: {
          color: string | null
          created_at: string
          created_by: string | null
          deleted_at: string | null
          id: string
          is_lost: boolean
          is_won: boolean
          name: string
          order_index: number
          probability_default: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          color?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          is_lost?: boolean
          is_won?: boolean
          name: string
          order_index: number
          probability_default: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          color?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          is_lost?: boolean
          is_won?: boolean
          name?: string
          order_index?: number
          probability_default?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      organizations: {
        Row: {
          active: boolean
          contract_prefix: string
          country_id: string | null
          created_at: string
          created_by: string | null
          default_currency: Database["public"]["Enums"]["currency_code"]
          deleted_at: string | null
          id: string
          legal_name: string | null
          logo_url: string | null
          name: string
          tax_id: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          active?: boolean
          contract_prefix: string
          country_id?: string | null
          created_at?: string
          created_by?: string | null
          default_currency?: Database["public"]["Enums"]["currency_code"]
          deleted_at?: string | null
          id?: string
          legal_name?: string | null
          logo_url?: string | null
          name: string
          tax_id?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          active?: boolean
          contract_prefix?: string
          country_id?: string | null
          created_at?: string
          created_by?: string | null
          default_currency?: Database["public"]["Enums"]["currency_code"]
          deleted_at?: string | null
          id?: string
          legal_name?: string | null
          logo_url?: string | null
          name?: string
          tax_id?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "organizations_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
        ]
      }
      payments: {
        Row: {
          amount: number
          contract_id: string
          created_at: string
          created_by: string | null
          currency: Database["public"]["Enums"]["currency_code"]
          deleted_at: string | null
          due_date: string | null
          id: string
          iva: number
          paid_at: string | null
          reference: string | null
          status: Database["public"]["Enums"]["payment_status"]
          type: Database["public"]["Enums"]["payment_type"]
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          amount: number
          contract_id: string
          created_at?: string
          created_by?: string | null
          currency: Database["public"]["Enums"]["currency_code"]
          deleted_at?: string | null
          due_date?: string | null
          id?: string
          iva?: number
          paid_at?: string | null
          reference?: string | null
          status?: Database["public"]["Enums"]["payment_status"]
          type: Database["public"]["Enums"]["payment_type"]
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          amount?: number
          contract_id?: string
          created_at?: string
          created_by?: string | null
          currency?: Database["public"]["Enums"]["currency_code"]
          deleted_at?: string | null
          due_date?: string | null
          id?: string
          iva?: number
          paid_at?: string | null
          reference?: string | null
          status?: Database["public"]["Enums"]["payment_status"]
          type?: Database["public"]["Enums"]["payment_type"]
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "payments_contract_id_fkey"
            columns: ["contract_id"]
            isOneToOne: false
            referencedRelation: "contracts"
            referencedColumns: ["id"]
          },
        ]
      }
      royalty_obligations: {
        Row: {
          amount: number
          contract_item_id: string | null
          created_at: string
          created_by: string | null
          currency: Database["public"]["Enums"]["currency_code"]
          deleted_at: string | null
          delivery_id: string | null
          genetic_program_id: string | null
          id: string
          paid_at: string | null
          qty_plants: number
          status: Database["public"]["Enums"]["royalty_status"]
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          amount: number
          contract_item_id?: string | null
          created_at?: string
          created_by?: string | null
          currency: Database["public"]["Enums"]["currency_code"]
          deleted_at?: string | null
          delivery_id?: string | null
          genetic_program_id?: string | null
          id?: string
          paid_at?: string | null
          qty_plants: number
          status?: Database["public"]["Enums"]["royalty_status"]
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          amount?: number
          contract_item_id?: string | null
          created_at?: string
          created_by?: string | null
          currency?: Database["public"]["Enums"]["currency_code"]
          deleted_at?: string | null
          delivery_id?: string | null
          genetic_program_id?: string | null
          id?: string
          paid_at?: string | null
          qty_plants?: number
          status?: Database["public"]["Enums"]["royalty_status"]
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "royalty_obligations_contract_item_id_fkey"
            columns: ["contract_item_id"]
            isOneToOne: false
            referencedRelation: "contract_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "royalty_obligations_delivery_id_fkey"
            columns: ["delivery_id"]
            isOneToOne: false
            referencedRelation: "deliveries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "royalty_obligations_genetic_program_id_fkey"
            columns: ["genetic_program_id"]
            isOneToOne: false
            referencedRelation: "genetic_programs"
            referencedColumns: ["id"]
          },
        ]
      }
      share_access_log: {
        Row: {
          country: string | null
          id: string
          ip: string | null
          opened_at: string
          share_id: string
          user_agent: string | null
        }
        Insert: {
          country?: string | null
          id?: string
          ip?: string | null
          opened_at?: string
          share_id: string
          user_agent?: string | null
        }
        Update: {
          country?: string | null
          id?: string
          ip?: string | null
          opened_at?: string
          share_id?: string
          user_agent?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "share_access_log_share_id_fkey"
            columns: ["share_id"]
            isOneToOne: false
            referencedRelation: "shares"
            referencedColumns: ["id"]
          },
        ]
      }
      shares: {
        Row: {
          created_at: string
          created_by: string | null
          deleted_at: string | null
          entity_id: string | null
          expires_at: string | null
          filter_json: Json | null
          id: string
          password_hash: string | null
          permissions: Database["public"]["Enums"]["share_permission"]
          scope: Database["public"]["Enums"]["share_scope"]
          title: string | null
          token: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          entity_id?: string | null
          expires_at?: string | null
          filter_json?: Json | null
          id?: string
          password_hash?: string | null
          permissions?: Database["public"]["Enums"]["share_permission"]
          scope: Database["public"]["Enums"]["share_scope"]
          title?: string | null
          token?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          entity_id?: string | null
          expires_at?: string | null
          filter_json?: Json | null
          id?: string
          password_hash?: string | null
          permissions?: Database["public"]["Enums"]["share_permission"]
          scope?: Database["public"]["Enums"]["share_scope"]
          title?: string | null
          token?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      species: {
        Row: {
          code: string | null
          created_at: string
          created_by: string | null
          deleted_at: string | null
          icon: string | null
          id: string
          name: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          code?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          icon?: string | null
          id?: string
          name: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          code?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          icon?: string | null
          id?: string
          name?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      user_client_assignments: {
        Row: {
          assigned_at: string
          client_id: string
          created_at: string
          created_by: string | null
          deleted_at: string | null
          id: string
          updated_at: string
          updated_by: string | null
          user_id: string
        }
        Insert: {
          assigned_at?: string
          client_id: string
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          updated_at?: string
          updated_by?: string | null
          user_id: string
        }
        Update: {
          assigned_at?: string
          client_id?: string
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          updated_at?: string
          updated_by?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_client_assignments_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_client_assignments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
        ]
      }
      varieties: {
        Row: {
          created_at: string
          created_by: string | null
          deleted_at: string | null
          genetic_program_id: string | null
          id: string
          is_active: boolean
          name: string
          royalty_per_plant: number | null
          species_id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          genetic_program_id?: string | null
          id?: string
          is_active?: boolean
          name: string
          royalty_per_plant?: number | null
          species_id: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          genetic_program_id?: string | null
          id?: string
          is_active?: boolean
          name?: string
          royalty_per_plant?: number | null
          species_id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "varieties_genetic_program_id_fkey"
            columns: ["genetic_program_id"]
            isOneToOne: false
            referencedRelation: "genetic_programs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "varieties_species_id_fkey"
            columns: ["species_id"]
            isOneToOne: false
            referencedRelation: "species"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      calendar_events: {
        Row: {
          client_id: string | null
          organization_id: string | null
          owner_id: string | null
          probability_pct: number | null
          qty: number | null
          source_id: string | null
          source_type: string | null
          status: string | null
          variety_id: string | null
          week: number | null
          year: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      current_user_role: {
        Args: never
        Returns: Database["public"]["Enums"]["user_role"]
      }
      is_admin: { Args: never; Returns: boolean }
      is_finance: { Args: never; Returns: boolean }
      is_sales: { Args: never; Returns: boolean }
      sales_can_write_client: {
        Args: { p_client_id: string }
        Returns: boolean
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
    }
    Enums: {
      activity_type: "call" | "email" | "meeting" | "task" | "note"
      amendment_type: "withdraw" | "modify" | "add"
      condition_type: "venta" | "reposicion" | "muestra"
      contract_status:
        | "borrador"
        | "por_revisar"
        | "firmado"
        | "en_proceso"
        | "finalizado"
        | "cancelado"
      currency_code: "CLP" | "USD" | "EUR"
      delivery_status: "pendiente" | "en_proceso" | "finalizado" | "eliminado"
      material_type: "vitro" | "raiz_cubierta" | "otros"
      payment_status: "pendiente" | "pagado" | "vencido"
      payment_type: "anticipo_1" | "anticipo_2" | "saldo"
      royalty_status: "no_califica" | "pendiente" | "pagado"
      sale_type: "nacional" | "exportacion"
      share_permission: "view" | "comment" | "edit_suggested"
      share_scope: "cliente" | "contrato" | "calendario" | "mapa" | "dashboard"
      user_role: "admin" | "sales" | "finance" | "viewer"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      activity_type: ["call", "email", "meeting", "task", "note"],
      amendment_type: ["withdraw", "modify", "add"],
      condition_type: ["venta", "reposicion", "muestra"],
      contract_status: [
        "borrador",
        "por_revisar",
        "firmado",
        "en_proceso",
        "finalizado",
        "cancelado",
      ],
      currency_code: ["CLP", "USD", "EUR"],
      delivery_status: ["pendiente", "en_proceso", "finalizado", "eliminado"],
      material_type: ["vitro", "raiz_cubierta", "otros"],
      payment_status: ["pendiente", "pagado", "vencido"],
      payment_type: ["anticipo_1", "anticipo_2", "saldo"],
      royalty_status: ["no_califica", "pendiente", "pagado"],
      sale_type: ["nacional", "exportacion"],
      share_permission: ["view", "comment", "edit_suggested"],
      share_scope: ["cliente", "contrato", "calendario", "mapa", "dashboard"],
      user_role: ["admin", "sales", "finance", "viewer"],
    },
  },
} as const
